export const ACTOR_KIND = {
  SYSTEM: "system",
  SERVICE: "service",
  VISITOR: "visitor",
  USER: "user",
  UNKNOWN: "unknown",
} as const;

export const AUTHENTICATION_REQUIREMENT = {
  REQUIRED: "AUTHENTICATION_REQUIRED",
  NOT_REQUIRED: "NO_AUTHENTICATION_REQUIRED",
} as const;

export const AUTHORIZATION_REQUIREMENT = {
  REQUIRED: "AUTHORIZATION_REQUIRED",
  NOT_REQUIRED: "NO_AUTHORIZATION_REQUIRED",
} as const;
